# Generated by Django 4.2.6 on 2023-10-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_area_remove_city_govern'),
        ('users', '0006_auto_20231006_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.area'),
        ),
    ]
