# Generated by Django 4.2.6 on 2023-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
