# Generated by Django 4.2.6 on 2023-11-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
