# Generated by Django 4.2.6 on 2023-11-06 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightsInfo', '0004_alter_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['day', 'time']},
        ),
        migrations.AddField(
            model_name='appointments',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flightsInfo.day'),
            preserve_default=False,
        ),
    ]
