# Generated by Django 4.2.6 on 2023-11-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='Fawry', max_length=20),
            preserve_default=False,
        ),
    ]
