# Generated by Django 4.2.6 on 2023-11-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_amount_payment_amount_cents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='payment_type',
        ),
    ]
