# Generated by Django 4.2.6 on 2023-10-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_chat_message_user_delete_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time']},
        ),
    ]
