# Generated by Django 4.2.6 on 2023-11-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='duration',
        ),
    ]
