# Generated by Django 4.2.6 on 2023-11-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
