# Generated by Django 4.2.6 on 2023-11-26 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_message_user_chat_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin_last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
