# Generated by Django 4.2.6 on 2023-10-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightsInfo', '0004_alter_package_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0005_reservation_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='package',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True)),
                ('passed_reservations', models.SmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flightsInfo.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.subscription'),
        ),
    ]
