# Generated by Django 4.2.6 on 2023-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservation_package_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_flight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_flight_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
