# Generated by Django 4.2.6 on 2023-11-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_subscription_first_flight_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='passed_reservations',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='started_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='reservations.subscription'),
        ),
    ]
