# Generated by Django 4.2.6 on 2023-11-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_program_auto_create'),
        ('reservations', '0009_alter_reservation_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flights.flight'),
        ),
    ]
