# Generated by Django 4.2.6 on 2023-10-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_area_remove_city_govern'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='move_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_from', to='locations.area'),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='move_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_to', to='locations.area'),
        ),
    ]
