# Generated by Django 4.2.6 on 2023-10-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flightdetails_move_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='duration',
            field=models.CharField(max_length=8),
        ),
    ]
