# Generated by Django 4.2.6 on 2023-10-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsInfo', '0002_alter_appointments_options'),
        ('flights', '0003_alter_flightdetails_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdetails',
            name='move_at',
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='move_at',
            field=models.ManyToManyField(to='flightsInfo.appointments'),
        ),
    ]
