# Generated by Django 4.2.6 on 2023-10-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_area_unique_together'),
        ('flightsInfo', '0002_alter_appointments_options'),
        ('flights', '0004_remove_flightdetails_move_at_flightdetails_move_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightDetails',
            new_name='Program',
        ),
    ]
