# Generated by Django 4.2.6 on 2023-10-09 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_flightdetails_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
