# Generated by Django 4.2.6 on 2023-10-10 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flight_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.SmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_count',
            field=models.SmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
