# Generated by Django 4.2.6 on 2023-10-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_flight_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
