# Generated by Django 4.2.6 on 2023-10-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_flight_price_program_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='available_seats',
            new_name='taken_seats',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='seats_count',
            new_name='total_seats',
        ),
    ]
