# Generated by Django 4.2.6 on 2023-10-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_rename_available_seats_flight_taken_seats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='details',
            new_name='program',
        ),
    ]
