# Generated by Django 4.2.6 on 2023-10-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_flight_options_rename_details_flight_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='cancelled',
            new_name='canceled',
        ),
    ]
