# Generated by Django 4.2.6 on 2023-10-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_alter_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
    ]
