# Generated by Django 4.2.6 on 2023-10-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_area_unique_together'),
        ('flights', '0016_remove_flight_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('move_from', 'move_to')},
        ),
    ]
