# Generated by Django 4.2.6 on 2023-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_alter_program_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
