# Generated by Django 4.2.6 on 2023-12-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_remove_flight_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(default='00:30:00'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('time', 'program', 'date')},
        ),
    ]
