# Generated by Django 4.2.6 on 2023-12-13 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0023_alter_program_duration_alter_flight_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
