# Generated by Django 4.2.6 on 2023-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('city', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='govern',
        ),
    ]
