# Generated by Django 4.2.6 on 2023-10-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flightdetails_move_from_and_more'),
        ('locations', '0002_area_remove_city_govern'),
        ('users', '0007_alter_user_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='area',
            name='govern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.govern'),
        ),
    ]
