# Generated by Django 4.2.6 on 2023-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_delete_city_area_govern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.BooleanField(default=True),
        ),
    ]
