# Generated by Django 4.2.6 on 2023-10-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_area_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'govern')},
        ),
    ]
